http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=DvirBenita
user.email=57675205+dvirofek1@users.noreply.github.com
user.mail=dvirbenita77@gmail.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/DvirBenita/Ex2.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.github.url=https://github.com/DvirBenita/Ex2
remote.github.fetch=+refs/heads/*:refs/remotes/github/*
remote.origin1.url=https://github.com/DvirBenita/Ex2
remote.origin1.fetch=+refs/heads/*:refs/remotes/origin1/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
